receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "127.0.0.1:4317"
      http:
        endpoint: "127.0.0.1:4318"
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - 127.0.0.1:8888
processors:
  batch:
    timeout: 2s
    
exporters:
  debug/basic:
    verbosity: basic

  debug/detailed:
    verbosity: detailed

  datadog:
    api:
      site: ${DD_SITE_PARAMETER}
      key: ${DD_API_KEY}
    hostname: testlab
      
connectors:
  datadog/connector:

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: "localhost"
                port: 8888      
    logs:
      level: info

  pipelines:
    metrics:
      receivers: [otlp, datadog/connector]
      processors: [batch]
      exporters: [debug/basic, datadog]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/basic, datadog/connector, datadog]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/basic, datadog]
